on:
  pull_request:
    branches:
      - main

jobs:
  analyze-tests:
    name: Analyze and Test New Version
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Config Local Git
        run: |
          git config --global user.email alexchamon@poli.ufrj.br
          git config --global user.name "TeaH4nd"
          
      - name: Check Merge to Development
        run: |
          git fetch --unshallow
          git checkout main
          git merge "origin/${{ github.head_ref }}"
          git checkout 1
          git merge master
          git checkout "origin/${{ github.head_ref }}"
