on:
  pull_request:
    branches:
      - main

jobs:
  analyze-tests:
    name: Analyze and Test New Version
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check Merge to Development
        run: |
          git fetch --unshallow
          git checkout main
          git merge "${{ github.head_ref }}"
          git checkout 1
          git merge master
          git checkout "${{ github.head_ref }}"
